name: Reputation
version: '${project.version}'
main: me.xaxis.reputation.ReputationMain
api-version: 1.19
authors: [Xaxis]
website: github.com/XaxisPlayz
depend: [PlaceholderAPI]
commands:
    reputation:
